#!/bin/bash -e

. vars.inc

BLDTIME=`date -u +%d-%m-%Y.%H:%M:%S`
GITHEAD=`git rev-parse --short HEAD`
VERSION=1.0 #`git describe --tags --abbrev=0 | sed 's/^v//' | sed 's/\+.*$$//'`

go env && go version
go fmt $proj_path
echo ""

echo "Building..."
go build \
	-ldflags "-X $proj_path/version.BLDTIME $BLDTIME -X $proj_path/version.GITHEAD $GITHEAD -X $proj_path/version.VERSION $VERSION" \
	-o bin/$proj_name $proj_path
echo ""

echo "OK"
