#!/bin/bash -e

. vars.inc

BLDTIME=`date -u +%d-%m-%Y.%H:%M:%S`
GITHEAD=`git rev-parse --short HEAD`
VERSION=1.0 #`git describe --tags --abbrev=0 | sed 's/^v//' | sed 's/\+.*$$//'`

go_build() {
	go fmt src
	echo "-> Build"
	go build \
		-ldflags "-X src/version.BLDTIME $BLDTIME -X src/version.GITHEAD $GITHEAD -X src/version.VERSION $VERSION" \
		-o bin/$PROJ_NAME src
	echo "OK"
}

go_build
