#!/bin/bash -e

. vars.inc

read -p "(Re) Installing external dependencies [y/n]? " YES
if [ "$YES" != 'y' ];
then
    	echo "bye"
        exit 1
fi

packages=(\
	"github.com/bradfitz/iter" \
	"github.com/golang/glog"\
	)

echo "Installing external dependencies"
rm -rf $GOPATH/pkg/*
for i in ${packages[*]}
do
	echo $i
	rm -rf $GOPATH/src/$i
	go get -d $i
	go install $i
done

cd ext
for i in ".hg*" ".git*" ".bzr*"
do
	find . -name $i -print0 | xargs -0 rm -rf
done
echo "OK"
