#!/bin/bash -e

. vars.inc

read -p "Update external packages [y/N]?" YES
if [ "$YES" != 'Y' ] && [ "$YES" != 'y' ];
then
    	echo "No? Then bye!"
        exit 1
fi

rm -rf $GOPATH/*
mkdir -p $GOPATH/src/$proj_path
ln -s ${PWD}/src/* $GOPATH/src/$proj_path

while read line
do
	if [ "$line" != '' ];
	then
		go get -d -v $line
		go install $line
	fi
done < pkgs.ext.txt

while read line
do
	if [ "$line" != '' ];
	then
		echo $proj_path/$line
		go install $proj_path/$line
	fi
done < pkgs.int.txt

cd ext
for i in ".hg*" ".git*" ".bzr*"
do
	find . -name $i -print0 | xargs -0 rm -rf
done

cd ..
echo "OK"
