#!/bin/bash -e

. vars.inc

# Internal packages which this project depends on.
packages_int=(\
	"version"
	)

# External packages which this project depends on.
packages_ext=(\
	"github.com/golang/glog"
	)

read -p "(Re) Installing external dependencies [y/N]?" YES
if [ "$YES" != 'Y' ] && [ "$YES" != 'y' ];
then
    	echo "No? Then bye!"
        exit 1
fi

rm -rf $GOPATH/*
mkdir -p $GOPATH/src/$proj_path && ln -s ${PWD}/src/* $GOPATH/src/$proj_path

echo "Installing external dependencies:"
for i in ${packages_int[*]}
do
	echo $proj_path/$i
	go install $proj_path/$i
done
for i in ${packages_ext[*]}
do
	echo $i
	go get -d $i
	go install $i
done

echo "Removing vcs folders..."
cd ext
for i in ".hg*" ".git*" ".bzr*"
do
	find . -name $i -print0 | xargs -0 rm -rf
done

cd ..
echo "OK"
