#!/bin/bash -e

. vars.inc

go_get_and_install () {
	rm -rf $GOPATH/*
	mkdir -p $GOPATH/src/$PROJ_PATH
	ln -s ${PWD}/src/* $GOPATH/src/$PROJ_PATH

	while read line
	do
		[[ "$line" =~ ^#.*$ ]] && continue
		if [ "$line" != '' ];
		then
			go get -d -v $line
		fi
	done < ./pkgs.txt

	go install $PROJ_PATH

	cd ext
	for i in ".hg*" ".git*" ".bzr*"
	do
		find . -name $i -print0 | xargs -0 rm -rf
	done
	cd ..

	go install $PROJ_PATH
	echo "OK"
}

confirm "Update external packages?" && go_get_and_install
