#!/bin/bash -e

. vars.inc

read -p "Update external packages [y/N]?" YES
if [ "$YES" != 'Y' ] && [ "$YES" != 'y' ];
then
    	echo "No? Then bye!"
        exit 1
fi

rm -rf $GOPATH/*
mkdir -p $GOPATH/src/$proj_path
ln -s ${PWD}/src/* $GOPATH/src/$proj_path

while read line
do
	[[ "$line" =~ ^#.*$ ]] && continue
	if [ "$line" != '' ];
	then
		go get -d -v $line
	fi
done < ./pkgs.txt

go install $proj_path

cd ext
for i in ".hg*" ".git*" ".bzr*"
do
	find . -name $i -print0 | xargs -0 rm -rf
done
cd ..

go install $proj_path
echo "OK"
