#!/bin/bash -e

. vars.inc

go_get_and_install() {
	rm -rf $GOPATH/*
	mkdir -p $GOPATH/src
	ln -s ${PWD}/src $GOPATH/src

	while read line
	do
		[[ "$line" =~ ^#.*$ ]] && continue
		if [ "$line" != '' ];
		then
			go get -d -v $line
		fi
	done < ./sync.txt

	pushd $GOPATH
	echo "removing revision control's system files..."
	for i in ".hg*" ".git*" ".bzr*"
	do
		find . -name $i -print0 | xargs -0 rm -rf
	done
	popd

	go install src
	echo "OK"
}

confirm "Update external packages?" && go_get_and_install
