#!/bin/sh

read -p "(Re) Installing external dependencies [y/n]? " YES
if [ "$YES" != "y" ];
then
	echo "bye"
	exit 1
fi

. $(dirname $0)/vars.inc

cd $ROOT
rm -rf $EXT
echo "Installing external dependencies"

for i in \
	"github.com/bradfitz/iter" \
	"github.com/golang/glog" \
	"github.com/davecgh/go-spew/spew" \
	"github.com/BurntSushi/toml"
do
	echo $i
	go get -d $i
	cd $EXT/src/$i
	go install
done

cd $EXT
for i in ".hg*" ".git*" ".bzr*"
do
	find . -name $i -print0 | xargs -0 rm -rf
done
echo "OK"
